default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      args: ["--target-version", "py310"]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args: ["--remove-all-unused-imports", "-i"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort (python)
